/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klassen;

/**
 *
 * @author Christian
 */
public class DialogNewTeams extends javax.swing.JDialog
{

  /**
   * Creates new form DialogNewTeams
   */
  public DialogNewTeams(java.awt.Frame parent, boolean modal,String teamNames[])
  {
    super(parent, modal);
    initComponents();
    tfPlace1Team1.setText(teamNames[0]);
    tfPlace1Team2.setText(teamNames[1]);
    tfPlace2Team1.setText(teamNames[2]);
    tfPlace2Team2.setText(teamNames[3]);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jPanel1 = new javax.swing.JPanel();
    btOk = new javax.swing.JButton();
    btCancel = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    tfPlace1Team1 = new javax.swing.JTextField();
    tfPlace1Team2 = new javax.swing.JTextField();
    jPanel4 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    tfPlace2Team1 = new javax.swing.JTextField();
    tfPlace2Team2 = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel1.setLayout(new java.awt.GridLayout());

    btOk.setText("ok");
    btOk.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        btOkActionPerformed(evt);
      }
    });
    jPanel1.add(btOk);

    btCancel.setText("abbrechen");
    btCancel.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        btCancelActionPerformed(evt);
      }
    });
    jPanel1.add(btCancel);

    getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

    jPanel2.setLayout(new java.awt.GridLayout(2, 1));

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Platz 1"));
    jPanel3.setLayout(new java.awt.GridLayout(2, 2));

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel1.setText("Team 1 Name");
    jPanel3.add(jLabel1);

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel2.setText("Team 2 Name");
    jPanel3.add(jLabel2);
    jPanel3.add(tfPlace1Team1);
    jPanel3.add(tfPlace1Team2);

    jPanel2.add(jPanel3);

    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Platz 2"));
    jPanel4.setLayout(new java.awt.GridLayout(2, 2));

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel3.setText("Team 1 Name");
    jPanel4.add(jLabel3);

    jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel4.setText("Team 2 Name");
    jPanel4.add(jLabel4);
    jPanel4.add(tfPlace2Team1);
    jPanel4.add(tfPlace2Team2);

    jPanel2.add(jPanel4);

    getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents
  
  private boolean ok=false;

  public boolean isOk()
  {
    return ok;
  }
  public String[] getTeamNames()
  {
    String[] str=new String[4];
    str[0]=tfPlace1Team1.getText();
    str[1]=tfPlace1Team2.getText();
    str[2]=tfPlace2Team1.getText();
    str[3]=tfPlace2Team2.getText();
    return str;
  }
  
  private void btCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btCancelActionPerformed
  {//GEN-HEADEREND:event_btCancelActionPerformed
    ok=false;
    setVisible(false);
  }//GEN-LAST:event_btCancelActionPerformed

  private void btOkActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btOkActionPerformed
  {//GEN-HEADEREND:event_btOkActionPerformed
    ok=true;
    setVisible(false);
  }//GEN-LAST:event_btOkActionPerformed

  /**
   * @param args the command line arguments
   */

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btCancel;
  private javax.swing.JButton btOk;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JTextField tfPlace1Team1;
  private javax.swing.JTextField tfPlace1Team2;
  private javax.swing.JTextField tfPlace2Team1;
  private javax.swing.JTextField tfPlace2Team2;
  // End of variables declaration//GEN-END:variables
}
